### ISSUE TITLE
header横向滑动列表异常

### ISSUE THREAD

**Issue by AntFate** [crasowas/easy_sticky_header#3]
header里是个横向滑动列表，在顶部时滑动到一半，纵向列表滑动上去之后，顶部sticky_header效果显露，stickey_header内的横向列表就自动滑回初始状态了，这个要怎么处理

**Comment by crasowas** [comment]
已经知道问题出在哪里，今天或明天会发新版本解决

**Comment by crasowas** [comment]
@AntFate 请将版本升级到1.1.0，然后使用`ScrollableStickyContainerBuilder`构建Header，参考[Example0](https://github.com/crasowas/easy_sticky_header/blob/main/example/lib/examples/example0.dart)。如果还有问题，欢迎评论👏

**Comment by AntFate** [comment]
好的，感谢
